<a href="https://colab.research.google.com/github/Centicini/AMR-Prediction-Single-Bacterial-Strain/blob/main/Deep_Learning_Mathematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, precision_score, recall_score

In [ ]:
print("Welcome to this coding tutorial")

Welcome to this coding tutorial


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier



#### Some Practice

In [14]:
#Scaler

a = np.array(5)
print("Scaler:", a)
print("Shape:", a.shape)


Scaler: 5
Shape: ()


In [15]:
#Vector
b = np.array([1, 2, 3])
print("Vector:", b)
print("Shape:", b.shape)

Vector: [1 2 3]
Shape: (3,)


In [17]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nMatrix:")
print(c)
print("Shape:", c.shape)


Matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [19]:
#3D Tensor

d = np.array([
    [[1, 2, 5, 6], [6, 6, 3, 4]],
    [[5, 4, 5, 6], [7, 8, 5, 4]]
])


print("\nTensor:")
print(d)
print("Shape:", d.shape)


Tensor:
[[[1 2 5 6]
  [6 6 3 4]]

 [[5 4 5 6]
  [7 8 5 4]]]
Shape: (2, 2, 4)


In [26]:
x = np.array([2, -3, 4])
w = np.array([-5, -6, 6])


dot_result = np.dot(x, w)
print(dot_result)

32


In [27]:
#Grayscale image

image = np.array([
    [0, 255],
    [128, 200]
])



print(image)
print(image.shape)

[[  0 255]
 [128 200]]
(2, 2)


In [28]:
#RGB Image

rgb_image = np.array([
    [[255, 0, 0], [0, 255, 0]],
    [[0, 0, 255], [255, 255, 0]]
])


print(rgb_image.shape)

(2, 2, 3)


In [29]:
#Let us perform some Basic Operations


x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

results = x + y
print(results)

[5 7 9]


In [30]:
result = x *y

print(result)

[ 4 10 18]


In [31]:
#Scaler multiplication

print(x * 3)



[3 6 9]


In [32]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

dot = np.dot(x, y)
print(dot)

32


In [33]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.dot(A, B)

print(result)

[[19 22]
 [43 50]]


In [35]:

e = np.array([7, 8, 9])

z = e + 3

print(z)

[10 11 12]


In [36]:
data = np.array([10, 20, 30, 40])

print("Mean:", np.mean(data))
print("Std:", data.std())

Mean: 25.0
Std: 11.180339887498949


In [37]:
t = tf.constant([1, 2, 3])

print(t)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [38]:
#Operations

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print(a +  b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [44]:
x = np.array([2, 3])
w = np.array([0.5, 1.5])
b = 1

z = np.dot(x, w) + b

print(z)

6.5


In [45]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

print(sigmoid(2))

0.8807970779778823


In [46]:
y_true = np.array([1, 0, 1])
y_pred = np.array([0.8, 0.2, 0.6])


mse = np.mean((y_true - y_pred)**2)

print(mse
      )

0.08


In [48]:
#Exercise
#createba scaler and print it's shape
d = np.array(4)

print("Shape:", d.shape)
print(d)

Shape: ()
4


In [50]:
fit = np.array([9, 0.4, 23.3, 22, 4])

print("Vector:", fit)
print("Shape of Vector:", fit.shape)

Vector: [ 9.   0.4 23.3 22.   4. ]
Shape of Vector: (5,)


In [51]:
bmi = np.array([
    [12, 6, 3],
    [7, 12, 43],
    [6, 3, 6]
])

bmi.shape

(3, 3)

In [52]:
print("BMI position:\n", bmi)

BMI position:
 [[12  6  3]
 [ 7 12 43]
 [ 6  3  6]]


In [53]:
#Print shape of [[1, 2], [3, 4], [5,6]]

tv = np.array([
    [[1, 2], [3, 4], [5, 6]]
])


print("tv shape:", tv.shape)

tv shape: (1, 3, 2)


In [55]:
#Vector Addition


num = np.array([1, 2, 3])
sop = np.array([10, 20, 30])


print(num + sop)


#this is element wise vector addition

[11 22 33]


In [56]:
print(num * 3)

[3 6 9]


In [59]:
print(sop** 3)

[ 1000  8000 27000]


In [61]:
#dot product
do_pro = np.dot(num, sop)

print(do_pro)

140


In [62]:
sup = np.array([5, 10, 15, 20])

print(sup.mean())

12.5


In [63]:
print(np.mean(sup))

12.5


In [64]:
fake_grey =np.array([
    [255, 0, 0],
    [0, 255, 0],
    [255, 255, 0]
])


print(fake_grey.shape)

(3, 3)


In [65]:
rgb_imaging = np.array(
    [
    [[232, 67, 9], [89, 67, 23]],
    [[123, 3, 27], [23, 27, 234]]

    ]
)


print("Shape of the RGB Image", rgb_imaging.shape)

Shape of the RGB Image (2, 2, 3)


In [66]:
a = tf.constant(10)


 print(a.shape)

()


In [67]:
b = tf.constant([1, 2, 3])

print(b.shape)

(3,)


In [68]:
c = tf.constant([[1, 2],
                 [3, 4]])


c.shape

TensorShape([2, 2])

In [69]:
#tensor (3D)

d = tf.constant([
    [[1, 2], [3, 4]],
    [[5,6], [7, 8]]
])


print("Scaler shape:", a.shape)
print("Vector Shape:", b.shape)
print("Matrix Shape:", c.shape)
print("Tensor shape:", d.shape)

Scaler shape: ()
Vector Shape: (3,)
Matrix Shape: (2, 2)
Tensor shape: (2, 2, 2)


In [76]:
broke = tf.constant([
    [10, 20, 30],
    [40, 50, 60]
])

print(broke)
print("Shape:", broke.shape)

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
Shape: (2, 3)


In [78]:
#first Row
x = tf.constant([
    [10, 20, 30],
    [40, 50, 60]
])



print(x[0])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [79]:
#to print Second row

print(x[1]
      )

tf.Tensor([40 50 60], shape=(3,), dtype=int32)


In [82]:
#element slicing second element in the first row

print(x[0][1])

tf.Tensor(20, shape=(), dtype=int32)


In [85]:
#Element wise operations for tensors


a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print(a + b)

print(a * b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [86]:
a = tf.constant([1 , 2, 3])
b = tf.constant(2)


print(a + b)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [91]:
A = tf.constant([
    [32, 34],
    [23, 11],
    [34, 78]
])


B = tf.constant([
    [2, 4, 23],
    [34, 12, 36]
])


compute = tf.matmul(A, B)

print(compute)

#the rows(n) must match the columns(n)

tf.Tensor(
[[1220  536 1960]
 [ 420  224  925]
 [2720 1072 3590]], shape=(3, 3), dtype=int32)


In [94]:
A = tf.constant([[1, 2, 3]])
B = tf.constant([[1, 2]])


#This will not run
#tf.matmul(A, B)

In [98]:
x = tf.constant([1, 2, 3, 4])
reshaped = tf.reshape(x, (2, 2))

print(reshaped)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [99]:
x =tf.constant([1, 2, 3])


x_new = tf.expand_dims(x, axis=0)

print(x_new)
print(x_new.shape)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


In [103]:
#Reduction Operations


x = tf.constant([1, 2, 3, 4], dtype=tf.float32)
print('Sum:', tf.reduce_sum(x))
print('Mean:', tf.reduce_mean(x))



Sum: tf.Tensor(10.0, shape=(), dtype=float32)
Mean: tf.Tensor(2.5, shape=(), dtype=float32)


In [104]:
#TENSORFLOW THINKING

x = tf.constant([[2.0, 3.0]])



In [105]:
x = tf.constant([[2.0, 3.0]]) #input
w = tf.constant([[0.5], [1.5]]) #weights

b = tf.constant([1.0]) #bias


z = tf.matmul(x, w) + b

print(z)

tf.Tensor([[6.5]], shape=(1, 1), dtype=float32)


In [110]:


#Exercises

#Creating a
# -scaler
# -vector
# -matrix

tom = tf.constant(13)
sam = tf.constant([23, 45, 21])
john = tf.constant([
    [23, 44, 21],
    [44, 2, 1]
])

print("Scaler Shape:", tom.shape)
print("Vector Shape:", sam.shape)
print("Matrix Shape:", john.shape)

Scaler Shape: ()
Vector Shape: (3,)
Matrix Shape: (2, 3)


In [111]:
boss = tf.constant([
    [10, 20],
    [30, 40],
    [50, 60]
])


print("Shape of Boss:", boss.shape)

Shape of Boss: (3, 2)


In [113]:
print("First row of boss:", boss[0])
print("Last element in first row of boss:", boss[0][-1 :])

First row of boss: tf.Tensor([10 20], shape=(2,), dtype=int32)
Last element in row of boss: tf.Tensor([20], shape=(1,), dtype=int32)


In [115]:
pred = tf.constant([
    [1, 2, 3]
])

fed = tf.constant([
    [10, 20, 30]
])


print(fed + pred)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [116]:
print(fed * 3)

tf.Tensor([30 60 90], shape=(3,), dtype=int32)


In [117]:
#Broadcasting


print(pred + 7)

tf.Tensor([ 8  9 10], shape=(3,), dtype=int32)


In [118]:
#Matrix multiplication

u = tf.constant([
    [1, 2],
    [5, 8]

])


y = tf.constant([
    [45, 23],
    [2, 7]
])



print("Matrix Product\n:", tf.matmul(u, y))

Matrix Product
: tf.Tensor(
[[ 49  37]
 [241 171]], shape=(2, 2), dtype=int32)


In [122]:
#Reshaping Values

mango = tf.constant([1, 2, 3, 4, 5, 6])

reshaper = tf.reshape(mango, (2, 3))
print(reshaper)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [124]:
#Expand Dimension


york = tf.constant([1, 2, 3])

new_york =tf.expand_dims(york, axis=1)

print(new_york)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [125]:
#Tensor Operations


zaid = tf.constant([10, 20, 30, 40])


print("sum is:", tf.reduce_sum(zaid))
print("Mean is:", tf.reduce_mean(zaid))

sum is: tf.Tensor(100, shape=(), dtype=int32)
Mean is: tf.Tensor(25, shape=(), dtype=int32)


In [126]:
#To cast to float

numer = tf.constant([12, 34, 23],tf.dtypes.float32)

print("New Mean of numer is:", tf.reduce_mean(numer))

New Mean of numer is: tf.Tensor(23.0, shape=(), dtype=float32)
